CREATE TABLE IF NOT EXISTS loads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id    INTEGER NOT NULL,   
    plate_id    INTEGER NOT NULL,   
    material_id     INTEGER NOT NULL,
    quantity     VARCHAR(50) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    signature    VARCHAR(100) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
    FOREIGN KEY (plate_id) REFERENCES plates(id) ON DELETE CASCADE
    FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE
    CHECK (payment_method IN ('CASH', 'INSTALLMENT'))
);

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name    VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS plates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id INTEGER NOT NULL,
    plate VARCHAR(50) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS materials (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name    VARCHAR(50) NOT NULL
);
