// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clients.sql

package db

import (
	"context"
)

const addClient = `-- name: AddClient :exec
INSERT INTO clients (name) 
VALUES ($1)
`

func (q *Queries) AddClient(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, addClient, name)
	return err
}

const getClientById = `-- name: GetClientById :one
SELECT name 
FROM clients
WHERE id = $1
`

func (q *Queries) GetClientById(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getClientById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getClients = `-- name: GetClients :many
SELECT 
    c.id,
    c.name
FROM clients c
`

func (q *Queries) GetClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, getClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
