// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Client struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Plate string `json:"plate"`
}

type Load struct {
	ID            int32  `json:"id"`
	Client        string `json:"client"`
	Plate         string `json:"plate"`
	Material      string `json:"material"`
	Quantity      string `json:"quantity"`
	Paymentmethod string `json:"paymentmethod"`
	Signature     string `json:"signature"`
}
