// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plates.sql

package db

import (
	"context"
)

const addPlate = `-- name: AddPlate :exec
INSERT INTO plates (client_id, plate) 
VALUES (?, ?)
`

type AddPlateParams struct {
	ClientID int64  `json:"client_id"`
	Plate    string `json:"plate"`
}

func (q *Queries) AddPlate(ctx context.Context, arg AddPlateParams) error {
	_, err := q.db.ExecContext(ctx, addPlate, arg.ClientID, arg.Plate)
	return err
}

const getPlatesByClientId = `-- name: GetPlatesByClientId :many
SELECT plate 
FROM plates 
WHERE client_id = ?
`

func (q *Queries) GetPlatesByClientId(ctx context.Context, clientID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPlatesByClientId, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var plate string
		if err := rows.Scan(&plate); err != nil {
			return nil, err
		}
		items = append(items, plate)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
